const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={expr:'',ans:0,answer:'0',memory:0,angle:'DEG',history:JSON.parse(localStorage.getItem('calcx-history')||'[]')};
const fmt=n=>{n=Number(n);if(!Number.isFinite(n))throw Error('Math error');if(Math.abs(n)<1e-12)n=0;return Number(n.toPrecision(12)).toString()};
function factorial(n){if(!Number.isInteger(n)||n<0||n>170)throw Error('Factorial needs a whole number ≤ 170');let r=1;for(let i=2;i<=n;i++)r*=i;return r}
function nCr(n,r){if(!Number.isInteger(n)||!Number.isInteger(r)||r<0||n<0||r>n)throw Error('Use whole numbers with 0 ≤ r ≤ n');return factorial(n)/(factorial(r)*factorial(n-r))}
function nPr(n,r){if(!Number.isInteger(n)||!Number.isInteger(r)||r<0||n<0||r>n)throw Error('Use whole numbers with 0 ≤ r ≤ n');return factorial(n)/factorial(n-r)}
function toRad(x){return state.angle==='DEG'?x*Math.PI/180:state.angle==='GRAD'?x*Math.PI/200:x}
function fromRad(x){return state.angle==='DEG'?x*180/Math.PI:state.angle==='GRAD'?x*200/Math.PI:x}
const fn={sin:x=>Math.sin(toRad(x)),cos:x=>Math.cos(toRad(x)),tan:x=>Math.tan(toRad(x)),asin:x=>fromRad(Math.asin(x)),acos:x=>fromRad(Math.acos(x)),atan:x=>fromRad(Math.atan(x)),sqrt:x=>{if(x<0)throw Error('Invalid square root');return Math.sqrt(x)},log:x=>{if(x<=0)throw Error('log needs a positive value');return Math.log10(x)},ln:x=>{if(x<=0)throw Error('ln needs a positive value');return Math.log(x)},abs:Math.abs,exp:Math.exp};

// A real parser: never eval(), understands the calculator's × and ÷ symbols,
// normal precedence, unary signs, factorial/percent, constants and functions.
function tokenize(input){
  const s=String(input).replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-').replaceAll('π','pi').replace(/\s+/g,'');
  const t=[]; let i=0;
  while(i<s.length){
    const c=s[i];
    if(/[0-9.]/.test(c)){
      const m=s.slice(i).match(/^(?:(?:\d+(?:\.\d*)?)|(?:\.\d+))(?:[eE][+-]?\d+)?/);
      if(!m)throw Error('Invalid number'); const v=Number(m[0]); if(!Number.isFinite(v))throw Error('Invalid number'); t.push({type:'num',value:v}); i+=m[0].length; continue;
    }
    if(/[A-Za-z]/.test(c)){
      const m=s.slice(i).match(/^[A-Za-z]+/)[0].toLowerCase(); i+=m.length;
      if(m==='pi')t.push({type:'num',value:Math.PI}); else if(m==='e')t.push({type:'num',value:Math.E}); else t.push({type:'fn',value:m}); continue;
    }
    if('+-*/^%!'.includes(c)){t.push({type:'op',value:c});i++;continue}
    if('()'.includes(c)){t.push({type:'paren',value:c});i++;continue}
    throw Error('Unknown character: '+c);
  }
  return t;
}
function evaluate(input){
  let t=tokenize(input),p=0;
  // Insert implicit multiplication: 2(3), 2sin(30), (2)(3), 2π.
  const canEnd=x=>x&&(x.type==='num'||(x.type==='paren'&&x.value===')')||(x.type==='op'&&['!','%'].includes(x.value)));
  const canStart=x=>x&&(x.type==='num'||x.type==='fn'||(x.type==='paren'&&x.value==='('));
  const u=[]; for(let i=0;i<t.length;i++){if(i&&canEnd(t[i-1])&&canStart(t[i]))u.push({type:'op',value:'*'});u.push(t[i])} t=u;
  const peek=()=>t[p]; const eat=()=>t[p++];
  function expression(){let v=term();while(peek()?.value==='+'||peek()?.value==='-'){const o=eat().value,r=term();v=o==='+'?v+r:v-r}return v}
  function term(){let v=power();while(peek()?.value==='*'||peek()?.value==='/'){const o=eat().value,r=power();if(o==='/'&&Math.abs(r)<1e-15)throw Error('Cannot divide by zero');v=o==='*'?v*r:v/r}return v}
  function power(){let v=unary();if(peek()?.value==='^'){eat();v=Math.pow(v,power())}return v}
  function unary(){if(peek()?.value==='+'){eat();return unary()}if(peek()?.value==='-'){eat();return -unary()}return post()}
  function post(){let v=primary();while(peek()?.value==='!'||peek()?.value==='%'){const o=eat().value;v=o==='!'?factorial(v):v/100}return v}
  function primary(){const q=peek();if(!q)throw Error('Incomplete expression');if(q.type==='num'){eat();return q.value}if(q.type==='paren'&&q.value==='('){eat();let v=expression();if(peek()?.value!==')')throw Error('Missing )');eat();return v}if(q.type==='fn'){const name=eat().value;if(peek()?.value!=='(')throw Error(name+' needs (');eat();let v=expression();if(peek()?.value!==')')throw Error('Missing )');eat();if(!(name in fn))throw Error('Unknown function: '+name);return fn[name](v)}throw Error('Unexpected input')}
  const r=expression();if(p!==t.length)throw Error('Invalid expression');return r;
}
function calculate(){if(!state.expr)return;try{const v=evaluate(state.expr);state.ans=v;state.answer=fmt(v);state.history.unshift({e:state.expr,a:state.answer});state.history=state.history.slice(0,50);render()}catch(e){state.answer='Error: '+e.message;render()}}
function render(){ $('#expression').textContent=state.expr||'0';$('#answer').textContent=state.answer;$('#angleLabel').textContent=state.angle;$('#memoryLabel').textContent=state.memory?'M '+fmt(state.memory):'';localStorage.setItem('calcx-history',JSON.stringify(state.history)) }
function add(v){state.expr+=v;render()}
const basic=[['MC','mem:mc'],['MR','mem:mr'],['M+','mem:plus'],['M−','mem:minus'],['AC','clear'],['(', '('],[')',')'],['%','%'],['x!','!'],['⌫','back'],['7','7'],['8','8'],['9','9'],['÷','/'],['√','sqrt('],['4','4'],['5','5'],['6','6'],['×','*'],['x²','^2'],['1','1'],['2','2'],['3','3'],['−','-'],['π','π'],['0','0'],['.','.'],['Ans','ans'],['+','+'],['=','calc']];
const sci=[['sin','sin('],['cos','cos('],['tan','tan('],['sin⁻¹','asin('],['cos⁻¹','acos('],['tan⁻¹','atan('],['log','log('],['ln','ln('],['√','sqrt('],['xʸ','^'],['abs','abs('],['eˣ','exp('],['e','e'],['π','π'],['(', '(']];
function buildPads(){ $('#keypad').innerHTML=basic.map(([l,v])=>`<button class="key ${/^\d|\.$/.test(l)?'num':''} ${['+','-','*','/'].includes(v)?'op':''} ${l==='='?'equal':''} ${['MC','MR','M+','M−'].includes(l)?'mem':''} ${l==='AC'?'clear':''} ${l==='0'?'zero':''}" data-v="${v}">${l}</button>`).join('');$('#sciencePad').innerHTML=sci.map(([l,v])=>`<button data-v="${v}"><b>${l}</b><small>${l}</small></button>`).join('');$$('[data-v]').forEach(b=>b.onclick=()=>key(b.dataset.v))}
function key(v){if(v==='clear'){state.expr='';state.answer='0'}else if(v==='back'){state.expr=state.expr.slice(0,-1)}else if(v==='calc'){calculate();return}else if(v==='ans'){state.expr+=fmt(state.ans)}else if(v.startsWith('mem:')){const x=Number(state.answer);if(v==='mem:mc')state.memory=0;else if(v==='mem:mr')state.expr+=fmt(state.memory);else if(Number.isFinite(x))state.memory+=v==='mem:plus'?x:-x}else add(v);render()}
function showView(view){$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#calcView').classList.toggle('hidden',view!=='calc'&&view!=='scientific');$('#matrixView').classList.toggle('hidden',view!=='matrix');$('#toolsView').classList.toggle('hidden',view!=='tools');$('#sciencePad').classList.toggle('hidden',view!=='scientific');$('#angleRow').classList.toggle('hidden',view!=='scientific')}
$$('.tab').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('.angle').forEach(b=>b.onclick=()=>{$$('.angle').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.angle=b.dataset.angle;render()});
// matrices
let n=2;const mats={A:[],B:[]};
function makeMat(){n=Number($('#matrixSize').value);for(const k of ['A','B']){const old=mats[k];mats[k]=Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>old[i]?.[j]??0));const el=$('#matrix'+k);el.style.gridTemplateColumns=`repeat(${n},1fr)`;el.innerHTML=mats[k].flatMap((row,i)=>row.map((v,j)=>`<input class="cell" data-m="${k}" data-i="${i}" data-j="${j}" value="${v||''}" inputmode="decimal">`)).join('')}$$('.cell').forEach(x=>x.oninput=()=>{mats[x.dataset.m][x.dataset.i][x.dataset.j]=Number(x.value)||0})}
function getM(k){return mats[k].map(r=>r.slice())} function addM(a,b,sgn=1){return a.map((r,i)=>r.map((x,j)=>x+sgn*b[i][j]))} function mul(a,b){return a.map(r=>b[0].map((_,j)=>r.reduce((s,x,k)=>s+x*b[k][j],0)))} function trans(a){return a[0].map((_,j)=>a.map(r=>r[j]))}
function det(a){if(a.length===1)return a[0][0];if(a.length===2)return a[0][0]*a[1][1]-a[0][1]*a[1][0];return a[0].reduce((s,x,j)=>s+(j%2?-1:1)*x*det(a.slice(1).map(r=>r.filter((_,k)=>k!==j))),0)}
function inv(a){const N=a.length,A=a.map(r=>r.slice()),I=A.map((r,i)=>r.map((_,j)=>i===j?1:0));for(let i=0;i<N;i++){let p=i;for(let k=i+1;k<N;k++)if(Math.abs(A[k][i])>Math.abs(A[p][i]))p=k;if(Math.abs(A[p][i])<1e-12)throw Error('Matrix is singular');[A[i],A[p]]=[A[p],A[i]];[I[i],I[p]]=[I[p],I[i]];const q=A[i][i];for(let j=0;j<N;j++){A[i][j]/=q;I[i][j]/=q}for(let k=0;k<N;k++)if(k!==i){const f=A[k][i];for(let j=0;j<N;j++){A[k][j]-=f*A[i][j];I[k][j]-=f*I[i][j]}}}return I}
function showMat(m){return m.map(r=>r.map(x=>fmt(x).padStart(12)).join(' ')).join('\n')}
const ops=[['A + B','add'],['A − B','sub'],['A × B','mul'],['det(A)','deta'],['det(B)','detb'],['A⁻¹','inva'],['B⁻¹','invb'],['Aᵀ','ta'],['Bᵀ','tb']];$('#matrixOps').innerHTML=ops.map(([l,v])=>`<button data-op="${v}">${l}</button>`).join('');$('#matrixOps').onclick=e=>{const o=e.target.dataset.op;if(!o)return;try{let r,a=getM('A'),b=getM('B');if(o==='add')r=showMat(addM(a,b));if(o==='sub')r=showMat(addM(a,b,-1));if(o==='mul')r=showMat(mul(a,b));if(o==='deta')r=fmt(det(a));if(o==='detb')r=fmt(det(b));if(o==='inva')r=showMat(inv(a));if(o==='invb')r=showMat(inv(b));if(o==='ta')r=showMat(trans(a));if(o==='tb')r=showMat(trans(b));$('#matrixResult').textContent=r}catch(e){$('#matrixResult').textContent='Error: '+e.message}};$('#matrixSize').onchange=makeMat;$$('[data-clear-matrix]').forEach(b=>b.onclick=()=>{mats[b.dataset.clearMatrix]=Array.from({length:n},()=>Array(n).fill(0));makeMat()});$('#matrixIdentity').onclick=()=>{for(const k of ['A','B'])mats[k]=Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>i===j?1:0));makeMat()};$('#matrixZeros').onclick=()=>{for(const k of ['A','B'])mats[k]=Array.from({length:n},()=>Array(n).fill(0));makeMat()};makeMat();
// tools + modals
const tools={equation:{title:'Equation Solver',html:`<div class="form"><label>Equation<input id="eq" placeholder="e.g. 2x + 5 = 17"></label></div><div class="actions"><button class="primary" onclick="solveEq()">Solve</button></div><div id="toolOut" class="output">Enter an equation.</div>`},statistics:{title:'Statistics',html:`<div class="form"><label>Data<input id="data" placeholder="e.g. 4, 7, 8, 10, 12"></label></div><div class="actions"><button class="primary" onclick="stats()">Calculate</button></div><div id="toolOut" class="output">Mean, median, variance and SD.</div>`},calculus:{title:'Calculus',html:`<div class="form"><label>f(x)<input id="fx" value="x^2 + 3*x"></label><div class="row"><label>x₀<input id="x0" value="2"></label><label>h<input id="h" value="0.0001"></label></div><label>Integrate from a to b (optional)<div class="row"><input id="a" placeholder="a"><input id="b" placeholder="b"></div></label></div><div class="actions"><button class="primary" onclick="calcTool()">Calculate</button></div><div id="toolOut" class="output"></div>`},convert:{title:'Conversions',html:`<div class="form"><div class="row"><label>Value<input id="cv" value="1"></label><label>Type<select id="ct"><option>km → mi</option><option>mi → km</option><option>°C → °F</option><option>°F → °C</option><option>kg → lb</option><option>lb → kg</option><option>rad → deg</option><option>deg → rad</option></select></label></div></div><div class="actions"><button class="primary" onclick="convert()">Convert</button></div><div id="toolOut" class="output"></div>`},base:{title:'Base-N Converter',html:`<div class="form"><div class="row"><label>Number<input id="bn" value="255"></label><label>From<select id="bf"><option>10</option><option>2</option><option>8</option><option>16</option></select></div></div><div class="actions"><button class="primary" onclick="base()">Convert</button></div><div id="toolOut" class="output"></div>`},combinatorics:{title:'Combinatorics',html:`<div class="form"><div class="row"><label>n<input id="cn" value="10"></label><label>r<input id="cr" value="3"></label></div></div><div class="actions"><button class="primary" onclick="comb()">Calculate</button></div><div id="toolOut" class="output"></div>`}};
function openTool(k){$('#modal').innerHTML=`<button class="close-modal" onclick="closeModal()">×</button><h2>${tools[k].title}</h2><p class="sub">All calculations run locally in your browser.</p>${tools[k].html}`;$('#modal').classList.remove('hidden');$('#backdrop').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden');$('#backdrop').classList.add('hidden')}$$('[data-tool]').forEach(b=>b.onclick=()=>openTool(b.dataset.tool));window.closeModal=closeModal;$('#backdrop').onclick=closeModal;
window.solveEq=()=>{try{let s=$('#eq').value.replace(/\s/g,'');let m=s.match(/^([+-]?\d*\.?\d*)x([+-]\d*\.?\d*)=([+-]?\d*\.?\d*)$/i);if(m){let A=Number(m[1]||1),B=Number(m[2]||0),C=Number(m[3]);$('#toolOut').textContent=Math.abs(A)<1e-15?(B===C?'All real numbers':'No solution'):'x = '+fmt((C-B)/A);return}let q=s.match(/^([+-]?\d*\.?\d*)x\^2([+-]\d*\.?\d*)x([+-]\d*\.?\d*)=0$/i);if(q){let A=Number(q[1]||1),B=Number(q[2]||0),C=Number(q[3]||0),D=B*B-4*A*C;if(D<0){let re=-B/(2*A),im=Math.sqrt(-D)/(2*A);$('#toolOut').textContent=`x₁ = ${fmt(re)} + ${fmt(im)}i\nx₂ = ${fmt(re)} − ${fmt(im)}i`}else $('#toolOut').textContent=`x₁ = ${fmt((-B+Math.sqrt(D))/(2*A))}\nx₂ = ${fmt((-B-Math.sqrt(D))/(2*A))}`;return}throw Error('Use ax + b = c or ax² + bx + c = 0')}catch(e){$('#toolOut').textContent='Error: '+e.message}};
window.stats=()=>{try{let a=$('#data').value.split(',').map(Number).filter(Number.isFinite);if(!a.length)throw Error('Enter numbers separated by commas');let s=a.reduce((x,y)=>x+y,0),mean=s/a.length,b=[...a].sort((x,y)=>x-y),med=b.length%2?b[(b.length-1)/2]:(b[b.length/2-1]+b[b.length/2])/2,pop=a.reduce((x,y)=>x+(y-mean)**2,0)/a.length,samp=a.length>1?a.reduce((x,y)=>x+(y-mean)**2,0)/(a.length-1):0;$('#toolOut').textContent=`Count: ${a.length}\nMean: ${fmt(mean)}\nMedian: ${fmt(med)}\nPopulation variance: ${fmt(pop)}\nPopulation SD: ${fmt(Math.sqrt(pop))}\nSample variance: ${fmt(samp)}\nSample SD: ${fmt(Math.sqrt(samp))}`}catch(e){$('#toolOut').textContent='Error: '+e.message}};
window.calcTool=()=>{try{const f=x=>Function('x','return '+$('#fx').value)(x),x=Number($('#x0').value),h=Number($('#h').value),d=(f(x+h)-f(x-h))/(2*h);let out='f\'(x₀) ≈ '+fmt(d);const a=Number($('#a').value),b=Number($('#b').value);if(Number.isFinite(a)&&Number.isFinite(b)){let N=1000,step=(b-a)/N,sum=f(a)+f(b);for(let i=1;i<N;i++)sum+=(i%2?4:2)*f(a+i*step);out+='\n∫ₐᵇ f(x)dx ≈ '+fmt(sum*step/3)}$('#toolOut').textContent=out}catch(e){$('#toolOut').textContent='Error: '+e.message}};
window.convert=()=>{try{let x=Number($('#cv').value),t=$('#ct').value,r={'km → mi':x*.621371,'mi → km':x/.621371,'°C → °F':x*9/5+32,'°F → °C':(x-32)*5/9,'kg → lb':x*2.2046226218,'lb → kg':x/2.2046226218,'rad → deg':x*180/Math.PI,'deg → rad':x*Math.PI/180}[t];$('#toolOut').textContent=fmt(r)}catch(e){$('#toolOut').textContent='Error: '+e.message}};
window.base=()=>{try{let b=Number($('#bf').value),v=parseInt($('#bn').value,b);if(!Number.isFinite(v))throw Error('Invalid number for selected base');$('#toolOut').textContent=`BIN  ${v.toString(2)}\nOCT  ${v.toString(8)}\nDEC  ${v}\nHEX  ${v.toString(16).toUpperCase()}`}catch(e){$('#toolOut').textContent='Error: '+e.message}};
window.comb=()=>{try{let n=Number($('#cn').value),r=Number($('#cr').value);$('#toolOut').textContent=`nCr = ${fmt(nCr(n,r))}\nnPr = ${fmt(nPr(n,r))}\nn!  = ${fmt(factorial(n))}`}catch(e){$('#toolOut').textContent='Error: '+e.message}};
const guides=[['01 · Basic calculations','Enter numbers and operators, then press =. The parser respects normal mathematical precedence.','25 × 4 + 10 = 110'],['02 · Scientific mode','Switch to Scientific for trigonometry, logarithms, powers and constants. Choose DEG, RAD or GRAD before trig calculations.','sin(30) = 0.5 in DEG'],['03 · Matrix mode','Choose a size, fill A and B, then select an operation. Determinant and inverse work for square matrices.','A × B · det(A) · A⁻¹ · Aᵀ'],['04 · Memory','MC clears memory. MR recalls it. M+ adds the displayed answer and M− subtracts it.','25 = → M+ → AC → MR'],['05 · Keyboard','Use numbers and operators directly. Enter calculates, Esc clears and Backspace deletes.','2*(3+4) ↵ = 14'],['06 · Tools','Equation Solver handles linear/quadratic equations, Statistics handles common descriptive measures, and Calculus uses numerical methods.','nCr(10,3) = 120']];function renderHelp(q=''){let x=guides.filter(g=>(g.join(' ')).toLowerCase().includes(q.toLowerCase()));$('#helpContent').innerHTML=x.map(g=>`<article class="guide"><h3>${g[0]}</h3><p>${g[1]}</p><div class="example">${g[2]}</div></article>`).join('')||'<p class="guide">No guide topics found.</p>'}$('#helpBtn').onclick=()=>{$('#drawer').classList.add('open');$('#backdrop').classList.remove('hidden');renderHelp()};$$('[data-close]').forEach(b=>b.onclick=()=>{$('#drawer').classList.remove('open');$('#backdrop').classList.add('hidden')});$('#helpSearch').oninput=e=>renderHelp(e.target.value);$('#historyBtn').onclick=()=>{let text=state.history.length?state.history.map((x,i)=>`${i+1}. ${x.e} = ${x.a}`).join('\n'):'No calculations yet.';$('#modal').innerHTML=`<button class="close-modal" onclick="closeModal()">×</button><h2>Calculation History</h2><p class="sub">Saved locally on this device.</p><div class="output">${text}</div><div class="actions"><button onclick="state.history=[];render();closeModal()">Clear history</button></div>`;$('#modal').classList.remove('hidden');$('#backdrop').classList.remove('hidden')};
window.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();calculate()}else if(e.key==='Escape'){state.expr='';state.answer='0';render()}else if(e.key==='Backspace'&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)){state.expr=state.expr.slice(0,-1);render()}else if(/^[0-9+\-*/().^%!]$/.test(e.key)&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)){add(e.key)}};
buildPads();render();showView('calc');
